### ISSUE TITLE
The V11 generation should be hidden if there are no ISR

### ISSUE THREAD

**Issue by epsitec** [epsitec/camt.li#10]
If the total number of ISR found in the dropped files is zero, it does not make sense to display a button to generate the V11 file.

**Comment by QJonny** [comment]
Isn't it already the case??
![screenshot](https://cloud.githubusercontent.com/assets/1978917/24654013/648d6190-1938-11e7-862f-32ff33367597.png)

**Comment by epsitec** [comment]
Errr... not for me with this file:

[CAMT053_310317.XML](https://github.com/epsitec/camt.li/files/893111/CAMT053_310317.txt)

![image](https://cloud.githubusercontent.com/assets/3872435/24656905/98cee404-1944-11e7-9303-0bf380979765.png)
