### ISSUE TITLE
Fix V11 download button in Internet Explorer

### ISSUE THREAD

**Issue by QJonny** [epsitec/camt.li#8]

**Comment by epsitec** [comment]
@QJonny on my IE 11, the download button works just great...

**Comment by epsitec** [comment]
@QJonny there might be a workaround for IE. See http://stackoverflow.com/questions/7405345/data-uri-scheme-and-internet-explorer-9-errors

**Comment by epsitec** [comment]
@QJonny can you please test this feature, again - Christoph told me it did not work for him in his Internet Explorer (not Edge). If we cannot get it to work on older browser, we should at least display a message telling the user that he should try another browser (e.g. Firefox or Chrome).

**Comment by QJonny** [comment]
Yes indeed, I'll have to use another way on IE /Edge... probably with msSaveBlob

**Comment by QJonny** [comment]
Version 1.3.4 does now support edge and internet explorer
